### ISSUE TITLE
不再提供展会的具体开闭时间

### ISSUE THREAD

**Issue by PaiJi** [FurCoder/furry-event-china#36]
大部分展会都不提供这一时间，目前网站上显示的是数据库默认GMT0时区时间，这可能会对用户带来误导。

**Comment by celeron533** [comment]
由于展会仅限于中国（以及港澳台），都在一个时区，在读取数据的时候或者UI渲染时直接UCT+8 ?
这一点比欧美不同时区好太多了

**Comment by PaiJi** [comment]
> 由于展会仅限于中国（以及港澳台），都在一个时区，在读取数据的时候或者UI渲染时直接UCT+8 ? 这一点比欧美不同时区好太多了

现在就是这么做的，但是大部分展会并不会提供这一时间，所以我现在按照经验写的是上午10点普通票进场，下午6点闭幕，实际时间可能和这个有出入，我担心用户真的会以这个时间去做行程安排。

**Comment by celeron533** [comment]
> > 由于展会仅限于中国（以及港澳台），都在一个时区，在读取数据的时候或者UI渲染时直接UCT+8 ? 这一点比欧美不同时区好太多了
> 
> 现在就是这么做的，但是大部分展会并不会提供这一时间，所以我现在按照经验写的是上午10点普通票进场，下午6点闭幕，实际时间可能和这个有出入，我担心用户真的会以这个时间去做行程安排。

那确实不需要提供了。由主办方网站自行决定和调整
